Repository PolicyEngine/policyengine-us, pull requests merged in 2024-05, with the labels that each got.

#4478 Improve LSR performance and fix bugs
  changelog_entry.yaml
  policyengine_us/parameters/gov/simulation/labor_supply_responses/elasticities/README.md
  policyengine_us/parameters/gov/simulation/labor_supply_responses/elasticities/income.yaml
  policyengine_us/parameters/gov/simulation/labor_supply_responses/elasticities/substitution.yaml
  policyengine_us/parameters/gov/simulation/labor_supply_responses/income_elasticity.yaml
  policyengine_us/parameters/gov/simulation/labor_supply_responses/substitution_elasticity.yaml
  policyengine_us/parameters/simulation/marginal_tax_rate_adults.yaml
  policyengine_us/tests/policy/baseline/household/marginal_tax_rate.yaml
  policyengine_us/variables/gov/simulation/labor_supply_response/labor_supply_response.py
  policyengine_us/variables/household/marginal_tax_rate.py
Labels: enhancement

#4488 Add macro impact caching for some variables
  changelog_entry.yaml
  policyengine_us/parameters/gov/household_refundable_state_credits.yaml
  policyengine_us/parameters/gov/household_tax_before_refundable_credits.yaml
  policyengine_us/variables/gov/local/tax/income/local_income_tax.py
  policyengine_us/variables/gov/ssa/state_supplement/state_supplement.py
  policyengine_us/variables/gov/states/ca/ca_child_care_subsidies.py
  policyengine_us/variables/gov/states/ca/calepa/carb/cvrp/ca_cvrp.py
  policyengine_us/variables/gov/states/co/ccap/co_ccap_subsidy.py
  policyengine_us/variables/gov/states/co/co_child_care_subsidies.py
  policyengine_us/variables/gov/usda/snap/snap.py
  policyengine_us/variables/gov/usda/wic/wic.py
  policyengine_us/variables/household/income/household/household_benefits.py
  policyengine_us/variables/household/income/household/household_refundable_state_tax_credits.py
  policyengine_us/variables/household/income/household/household_refundable_tax_credits.py
  policyengine_us/variables/household/income/household/household_state_benefits.py
  policyengine_us/variables/household/income/household/household_state_income_tax.py
  policyengine_us/variables/household/income/household/household_state_tax_before_refundable_credits.py
  policyengine_us/variables/household/income/household/household_tax_before_refundable_credits.py
Labels: enhancement

#4498 Add CBO splits for labor supply, and self-employment responses
  changelog_entry.yaml
  policyengine_us/parameters/gov/contrib/cbo/labor_supply/README.md
  policyengine_us/parameters/gov/contrib/cbo/labor_supply/elasticities.yaml
  policyengine_us/parameters/gov/simulation/labor_supply_responses/elasticities/income.yaml
  policyengine_us/parameters/gov/simulation/labor_supply_responses/elasticities/substitution.yaml
  policyengine_us/system.py
  policyengine_us/variables/gov/simulation/labor_supply_response/labor_supply_response.py
  policyengine_us/variables/household/marginal_tax_rate.py
  policyengine_us/variables/input/income.py
Labels: enhancement

#4508 Allow PUF files to be user-provided
  changelog_entry.yaml
  policyengine_us/data/datasets/cps/enhanced_cps/process_puf.py
  policyengine_us/data/datasets/puf/puf.py
Labels: enhancement

#4277 Add 2023 Missouri Tax Rules
  changelog_entry.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/credits/non_refundable.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/credits/property_tax/age_threshold.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/credits/property_tax/income_offset/joint_owner.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/credits/property_tax/income_offset/joint_renter.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/credits/property_tax/income_offset/non_joint.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/credits/property_tax/phase_out/threshold.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/credits/property_tax/property_tax_limit.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/credits/property_tax/property_tax_rent_ratio.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/credits/property_tax/rent_property_tax_limit.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/credits/wftc/match.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/deductions/business_income/rate.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/deductions/mo_max_social_security_benefit.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/minimum_taxable_income.yaml
  policyengine_us/parameters/gov/states/mo/tax/income/rates.yaml
  policyengine_us/tests/policy/baseline/gov/states/mo/tax/income/credits/wftc/mo_wftc.yaml
  policyengine_us/tests/policy/baseline/gov/states/mo/tax/income/deductions/mo_business_income_deduction.yaml
  policyengine_us/tests/policy/baseline/gov/states/mo/tax/income/deductions/mo_pension_and_ss_or_ssd_deduction/mo_pension_and_ss_or_ssd_deduction_section_a.yaml
  policyengine_us/tests/policy/baseline/gov/states/mo/tax/income/income_tax/mo_income_tax_before_credits.yaml
  policyengine_us/tests/policy/baseline/gov/states/mo/tax/income/income_tax/mo_income_tax_exempt.yaml
  policyengine_us/variables/gov/states/mo/tax/income/credits/mo_wftc.py
  policyengine_us/variables/gov/states/mo/tax/income/credits/property_tax/mo_property_tax_credit.py
  policyengine_us/variables/gov/states/mo/tax/income/credits/property_tax/mo_ptc_gross_income.py
  policyengine_us/variables/gov/states/mo/tax/income/credits/property_tax/mo_ptc_income_offset.py
  policyengine_us/variables/gov/states/mo/tax/income/credits/property_tax/mo_ptc_net_income.py
  policyengine_us/variables/gov/states/mo/tax/income/credits/property_tax/mo_ptc_taxunit_eligible.py
  policyengine_us/variables/gov/states/mo/tax/income/deductions/mo_business_income_deduction.py
  policyengine_us/variables/gov/states/mo/tax/income/deductions/mo_federal_income_tax_deduction.py
  policyengine_us/variables/gov/states/mo/tax/income/deductions/mo_itemized_deductions.py
  policyengine_us/variables/gov/states/mo/tax/income/deductions/mo_pension_and_ss_or_ssd_deduction.py
  policyengine_us/variables/gov/states/mo/tax/income/deductions/mo_pension_and_ss_or_ssd_deduction_section_a.py
  policyengine_us/variables/gov/states/mo/tax/income/deductions/mo_pension_and_ss_or_ssd_deduction_section_b.py
  policyengine_us/variables/gov/states/mo/tax/income/deductions/mo_pension_and_ss_or_ssd_deduction_section_c.py
  policyengine_us/variables/gov/states/mo/tax/income/subtractions/mo_qualified_health_insurance_premiums.py
Labels: enhancement, states/mo

#4539 Add weekly hours worked
  changelog_entry.yaml
  policyengine_us/data/datasets/cps/cps.py
  policyengine_us/data/datasets/cps/raw_cps.py
  policyengine_us/system.py
  policyengine_us/variables/household/expense/retirement/able_contributions_person.py
  policyengine_us/variables/household/income/person/weekly_hours_worked.py
Labels: enhancement

#4554 State tax reforms produce no impact in microsimulation
  changelog_entry.yaml
  policyengine_us/system.py
Labels: bug
