Repository PolicyEngine/policyengine-us, pull requests merged in 2024-10, with the labels that each got.

#5094 Always use the SUA for CO
  changelog_entry.yaml
  policyengine_us/parameters/gov/usda/snap/income/deductions/utility/always_standard.yaml
  policyengine_us/tests/policy/baseline/gov/usda/snap/income/deductions/snap_state_using_standard_utility_allowance.yaml
  policyengine_us/tests/policy/baseline/gov/usda/snap/income/deductions/snap_utility_allowance_type.yaml
  policyengine_us/variables/gov/usda/snap/income/deductions/shelter/snap_state_using_standard_utility_allowance.py
  policyengine_us/variables/gov/usda/snap/income/deductions/shelter/snap_utility_allowance_type.py
Labels: snap, states/co

#5169 Add EITC takeup
  changelog_entry.yaml
  policyengine_us/parameters/gov/irs/credits/eitc/takeup.yaml
  policyengine_us/tests/policy/baseline/household/marginal_tax_rate.yaml
  policyengine_us/variables/gov/irs/credits/earned_income/eitc.py
  policyengine_us/variables/gov/irs/credits/earned_income/takes_up_eitc.py
Labels: enhancement

#5174 Update US data
  changelog_entry.yaml
  setup.py
Labels: data

#5182 Update us-data to 1.10
  changelog_entry.yaml
  policyengine_us/tests/policy/baseline/household/marginal_tax_rate.yaml
  policyengine_us/variables/gov/irs/credits/earned_income/takes_up_eitc.py
  policyengine_us/variables/gov/usda/snap/takes_up_snap_if_eligible.py
  setup.py
Labels: data

#5249 Pregnant person counted as 2 for Medicaid (and CHP+)
  changelog_entry.yaml
  policyengine_us/tests/policy/baseline/gov/hhs/medicaid/income/tax_unit_medicaid_income_level.yaml
  policyengine_us/variables/gov/hhs/medicaid/income/tax_unit_medicaid_income_level.py
  policyengine_us/variables/gov/hhs/tax_unit_fpg.py
  policyengine_us/variables/household/demographic/person/current_pregnancies.py
  policyengine_us/variables/household/demographic/person/is_pregnant.py
Labels: medicaid

#5277 Capital gains behavioral response
  changelog_entry.yaml
  policyengine_us/parameters/gov/simulation/capital_gains_responses/elasticity.yaml
  policyengine_us/system.py
  policyengine_us/variables/gov/simulation/capital_gains_responses.py
  policyengine_us/variables/household/income/person/capital_gains/long_term_capital_gains.py
  policyengine_us/variables/input/geography.py
Labels: enhancement
